[FTSU-190] Fences to order memory accesses and synchronize interrupts
sifive/example-buserror pull request #3
Opened 2020-06-14 22:31 UTC by johningalls-sifive

In the RISC-V Weak Memory Ordering Model, a `fence` instruction is required to ensure ordering between memory accesses to different addresses.

2020-06-14 22:36 UTC, johningalls-sifive commented
this fix passes `wake -x 'test Verilator exampleTests noObfuscation standardCore "u84"'`

2020-06-15 16:20 UTC, nategraff-sifive requested changes
Thanks John! Would you mind indenting the inline assembly to match the rest of the file? It looks like this file is using tabs.

2020-06-15 18:34 UTC, johningalls-sifive commented
tabs?!  can I change the whole file to use spaces?

2020-06-15 18:35 UTC, nategraff-sifive commented
> tabs?! can I change the whole file to use spaces?

I had a hunch you might ask :) Go ahead

2020-06-15 20:00 UTC, nategraff-sifive approved these changes

2020-06-15 20:11 UTC, merged